(()=>{'use strict';
const routes=[['dashboard','Tableau de bord'],['proposals','Propositions'],['calendar','Calendrier'],['profile','Profil'],['stats','Statistiques'],['history','Historique']];
let data=null,route='dashboard',current=null;
const $=q=>document.querySelector(q),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const badge=s=>`<span class="badge ${s==='Active'||s==='Validé'?'green':s==='Proposition'?'blue':'orange'}">${esc(s)}</span>`;
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2200)}
async function load(){try{const r=await fetch('data.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error();data=await r.json();render();const d=new Date(data.lastSync);$('#lastSync').textContent='Dernière mise à jour : '+d.toLocaleString('fr-FR')}catch{$('#app').innerHTML='<div class="card">Impossible de charger les données. Réessaie dans quelques instants.</div>'}}
function nav(){const buttons=routes.map(([r,l])=>`<button class="nav-btn ${route===r?'active':''}" data-route="${r}">${l}</button>`).join('');$('#nav').innerHTML=buttons;$('#bottomNav').innerHTML=routes.slice(0,5).map(([r,l])=>`<button class="${route===r?'active':''}" data-route="${r}">${l}</button>`).join('')}
function metric(label,value,foot){return `<article class="card metric"><label>${label}</label><strong>${value}</strong><span>${foot}</span></article>`}
function postCard(p){return `<article class="card post-card"><div class="status">${badge(p.status)}<span class="badge">${p.date} · ${p.time}</span></div><h3>${esc(p.title)}</h3><div class="hook">${esc(p.hook)}</div><div class="excerpt">${esc(p.body)}</div><div class="reason"><strong>Pourquoi cette idée ?</strong><br>${esc(p.reason)}</div><div class="actions"><button class="btn primary" data-open="${p.id}">Ouvrir</button><button class="btn success" data-validate="${p.id}">Valider</button></div></article>`}
function dashboard(){return `<section class="hero"><div><span class="badge blue">CHATGPT → APPLICATION</span><h2>Ton espace LinkedIn, clair et à jour.</h2><p>ChatGPT prépare les contenus à partir de tes tournées, visites, apprentissages et retours. L’application les rassemble pour que tu puisses les lire, comparer et valider facilement.</p><button class="btn primary" data-route="proposals">Voir les 3 propositions</button></div><div class="hero-stat"><strong>${data.posts.filter(p=>p.status==='Proposition').length}</strong><span>idées prêtes</span></div></section><div class="section"><div><h2>Vue d’ensemble</h2><p>Données synchronisées depuis ChatGPT.</p></div></div><section class="grid g4">${metric('Propositions',data.posts.length,'Prêtes à examiner')}${metric('Score du profil',data.profile.score+'/100','Positionnement cohérent')}${metric('Impressions',data.stats.weeklyImpressions.toLocaleString('fr-FR'),'Donnée enregistrée')}${metric('Engagement',data.stats.engagement+' %','À confirmer avec LinkedIn')}</section><div class="section"><div><h2>Priorités du moment</h2></div></div><section class="grid g3">${data.posts.slice(0,3).map(postCard).join('')}</section><div class="section"><div><h2>Automatisations ChatGPT</h2></div></div><div class="card">${data.tasks.map(t=>`<div class="list-row"><div><strong>${esc(t.title)}</strong><span>${esc(t.schedule)}</span></div>${badge(t.status)}</div>`).join('')}</div>`}
function proposals(){return `<div class="section"><div><h2>Propositions préparées par ChatGPT</h2><p>Trois angles différents, sans publication automatique.</p></div></div><section class="grid g3">${data.posts.map(postCard).join('')}</section>`}
function calendar(){const days=['Lundi','Mardi','Mercredi','Jeudi','Vendredi'];return `<div class="section"><div><h2>Calendrier éditorial</h2><p>Planning conseillé pour la semaine.</p></div></div><section class="calendar">${days.map((d,i)=>{const p=data.posts[i]||null;return `<div class="day"><h3>${d}</h3>${p?`<div class="cal-item" data-open="${p.id}">${badge(p.status)}<strong>${esc(p.title)}</strong><span>${p.time} · ${esc(p.type)}</span></div>`:'<span class="badge">Libre</span>'}</div>`}).join('')}</section>`}
function profile(){return `<div class="section"><div><h2>Profil LinkedIn</h2><p>Version de référence conservée dans ChatGPT.</p></div></div><section class="grid g2"><article class="card"><span class="badge green">Score ${data.profile.score}/100</span><h2 class="profile-title">${esc(data.profile.title)}</h2><div class="progress"><i style="width:${data.profile.score}%"></i></div><div class="section"><div><h2>Compétences</h2></div></div><div class="chips">${data.profile.skills.map(s=>`<span class="badge">${esc(s)}</span>`).join('')}</div></article><article class="card"><h2>Résumé</h2><p class="summary">${esc(data.profile.summary)}</p></article></section>`}
function stats(){return `<div class="section"><div><h2>Statistiques enregistrées</h2><p>Les données réelles doivent venir de LinkedIn ou de captures envoyées à ChatGPT.</p></div></div><section class="grid g4">${metric('Abonnés',data.stats.followers,'Valeur enregistrée')}${metric('Visites du profil',data.stats.profileViews,'Période précédente')}${metric('Impressions',data.stats.weeklyImpressions.toLocaleString('fr-FR'),'Semaine')}${metric('Engagement',data.stats.engagement+' %','Estimation enregistrée')}</section><div class="section"><div><h2>Thèmes les plus efficaces</h2></div></div><article class="card">${data.stats.themes.map(t=>`<div class="theme"><span>${esc(t[0])}</span><div class="progress"><i style="width:${t[1]}%"></i></div><strong>${t[1]}</strong></div>`).join('')}</article>`}
function history(){return `<div class="section"><div><h2>Historique ChatGPT</h2><p>Dernières synchronisations et décisions.</p></div></div><article class="card">${data.history.map(h=>`<div class="list-row"><div><strong>${esc(h[1])}</strong><span>${esc(h[0])} · ${esc(h[2])}</span></div></div>`).join('')}</article>`}
function render(){if(!data)return;nav();const map={dashboard,proposals,calendar,profile,stats,history};$('#pageTitle').textContent=routes.find(r=>r[0]===route)?.[1]||'Tableau de bord';$('#app').innerHTML=map[route]();}
function openPost(id){current=data.posts.find(p=>p.id===id);if(!current)return;$('#dialogTitle').textContent=current.title;$('#dialogBody').innerHTML=`<div class="full-post"><strong>${esc(current.hook)}</strong>\n\n${esc(current.body)}\n\n${esc(current.cta)}\n\n${current.hashtags.map(esc).join(' ')}\n\nVisuel conseillé : ${esc(current.visual)}</div>`;$('#postDialog').showModal()}
document.addEventListener('click',e=>{const r=e.target.closest('[data-route]');if(r){route=r.dataset.route;render();return}const o=e.target.closest('[data-open]');if(o)openPost(o.dataset.open);const v=e.target.closest('[data-validate]');if(v){const p=data.posts.find(x=>x.id===v.dataset.validate);p.status='Validé';render();toast('Validé dans l’application. Dis-le ensuite à ChatGPT pour synchroniser l’historique.')}});
$('#refreshBtn').onclick=load;$('#closeDialog').onclick=()=>$('#postDialog').close();$('#copyPost').onclick=()=>{if(!current)return;navigator.clipboard?.writeText(`${current.hook}\n\n${current.body}\n\n${current.cta}\n\n${current.hashtags.join(' ')}`);toast('Publication copiée')};$('#validatePost').onclick=()=>{if(!current)return;current.status='Validé';$('#postDialog').close();render();toast('Validé localement')};
load();})();