(()=>{
const old=JSON.parse(localStorage.getItem(window.CRM_STORAGE_KEY)||'{}');
state.customProspects=old.customProspects||[];state.prospectEdits=old.prospectEdits||{};
state.prospects.forEach(p=>Object.assign(p,state.prospectEdits[p.id]||{}));
state.customProspects.forEach(p=>{if(!companyById(p.id))state.prospects.push(p)});
const saveAll=()=>localStorage.setItem(window.CRM_STORAGE_KEY,JSON.stringify({history:state.history,tour:state.tour,orders:state.orders,newContacts:state.newContacts,customProspects:state.customProspects,prospectEdits:state.prospectEdits}));
function addProspectButton(){if(document.querySelector('#addProspectBtn'))return;const b=document.createElement('button');b.id='addProspectBtn';b.className='primary-wide';b.textContent='Ajouter un prospect';b.onclick=()=>openProspectForm();document.querySelector('#prospects .page-head').after(b)}
function openProspectForm(p=null){let d=document.querySelector('#prospectDialog');if(!d){d=document.createElement('dialog');d.id='prospectDialog';d.innerHTML=`<form id="prospectForm"><div class="dialog-head"><h2>Fiche prospect</h2><button type="button" onclick="prospectDialog.close()">×</button></div><label>Société<input id="pName" required></label><label>SIRET<input id="pSiret"></label><label>Adresse<textarea id="pAddress" rows="3"></textarea></label><label>Département<input id="pDept" maxlength="3"></label><label>Contact / dirigeant<input id="pManager"></label><label>Téléphone<input id="pPhone"></label><label>E-mail<input id="pEmail" type="email"></label><label>Statut<select id="pStatus"><option>Non visité</option><option>À relancer</option><option>Devis envoyé</option><option>Attente 1ère commande</option><option>Client</option><option>À supprimer</option></select></label><button class="primary-wide">Enregistrer</button></form>`;document.body.appendChild(d);document.querySelector('#prospectForm').onsubmit=e=>{e.preventDefault();saveProspect()}}d.dataset.editId=p?.id||'';p=p||{};pName.value=p.name||'';pSiret.value=p.siret||'';pAddress.value=p.address||'';pDept.value=p.dept||'';pManager.value=p.manager||'';pPhone.value=p.phone||'';pEmail.value=p.email||'';pStatus.value=p.status||'Non visité';d.showModal()}
function saveProspect(){const d=prospectDialog,id=d.dataset.editId,data={name:pName.value.trim(),siret:pSiret.value.trim(),address:pAddress.value.trim(),dept:pDept.value.trim(),manager:pManager.value.trim(),phone:pPhone.value.trim(),email:pEmail.value.trim(),status:pStatus.value};if(id){const p=companyById(id);Object.assign(p,data);const c=state.customProspects.find(x=>String(x.id)===String(id));if(c)Object.assign(c,data);else state.prospectEdits[id]=data;if(window.CRM_USER==='manager'){let shared={};try{shared=JSON.parse(localStorage.getItem('crmTechnimat:sharedClientEdits')||'{}')}catch{}shared[id]=data;localStorage.setItem('crmTechnimat:sharedClientEdits',JSON.stringify(shared))}}else{const p={id:'custom-'+Date.now(),...data};state.prospects.push(p);state.customProspects.push(p)}saveAll();d.close();initFilters();renderProspects();renderDashboard()}
window.editProspect=id=>{companyDialog.close();openProspectForm(companyById(id))};
const originalOpen=window.openCompany;window.openCompany=id=>{originalOpen(id);const p=companyById(id),body=document.querySelector('#companyBody');if(p&&body&&!body.querySelector('.edit-prospect')){const b=document.createElement('button');b.className='primary-wide edit-prospect';b.textContent='Modifier la fiche';b.onclick=()=>window.editProspect(id);body.querySelector('.row')?.after(b)}};
function openExistingVisit(v){const sel=document.querySelector('#visitCompany');sel.innerHTML=state.prospects.map(p=>`<option value="${esc(p.id)}" ${String(p.id)===String(v.companyId)?'selected':''}>${esc(p.name)}</option>`).join('');visitDate.value=v.date||'';visitPerson.value=v.person||'';visitFunction.value=v.role||'';visitContactMethod.value=v.contactMethod||'';visitSummary.value=v.summary||'';visitNeeds.value=v.needs||'';visitNext.value=v.next||'';visitBestTime.value=v.bestTime||'';visitFollowup.value=v.followup||'';visitForm.dataset.editId=v.id;visitDialog.showModal()}
window.editVisit=id=>{const v=state.history.find(x=>String(x.id)===String(id));if(v)openExistingVisit(v)};
window.deleteVisit=id=>{if(!confirm('Supprimer ce compte rendu ?'))return;state.history=state.history.filter(v=>String(v.id)!==String(id));saveAll();renderHistory();renderDashboard();renderRelances()};
renderHistory=function(){const h=[...state.history].sort((a,b)=>String(b.date).localeCompare(String(a.date)));historyList.innerHTML=h.length?h.map(v=>`<article class="item"><h3>${esc(v.companyName)}</h3><p>${esc(v.date)} — ${esc(v.person||'Interlocuteur non précisé')}</p>${v.contactMethod?`<p><b>Moyen :</b> ${esc(v.contactMethod)}</p>`:''}<p>${esc(v.summary)}</p>${v.bestTime?`<p><b>Meilleur moment :</b> ${esc(v.bestTime)}</p>`:''}${v.followup?`<span class="badge red">Relance ${esc(v.followup)}</span>`:''}<div class="item-actions"><button onclick="editVisit('${esc(v.id)}')">Modifier</button><button class="secondary" onclick="deleteVisit('${esc(v.id)}')">Supprimer</button></div></article>`).join(''):'<p class="empty">Aucun compte rendu enregistré.</p>'};
const oldSubmit=visitForm.onsubmit;visitForm.addEventListener('submit',e=>{const id=visitForm.dataset.editId;if(!id)return;e.preventDefault();e.stopImmediatePropagation();const p=companyById(visitCompany.value),i=state.history.findIndex(v=>String(v.id)===String(id));if(i>=0)state.history[i]={id,companyId:p.id,companyName:p.name,date:visitDate.value,person:visitPerson.value,role:visitFunction.value,contactMethod:visitContactMethod.value,summary:visitSummary.value,needs:visitNeeds.value,next:visitNext.value,bestTime:visitBestTime.value,followup:visitFollowup.value};visitForm.dataset.editId='';saveAll();visitDialog.close();visitForm.reset();renderDashboard();renderHistory();renderRelances()},true);
addProspectButton();initFilters();renderProspects();renderHistory();renderDashboard();
})();
