const activeUser=window.CRM_USER||'locked';
let managerSettings={startAddress:'TECHNIMAT, Narbonne',tourSize:6,notifications:true};
try{managerSettings={...managerSettings,...JSON.parse(localStorage.getItem('crmTechnimat:managerSettings')||'{}')}}catch{}
const storageKey=window.CRM_STORAGE_KEY||`crmTechnimat:${activeUser}`;
if(activeUser==='vincent'&&!localStorage.getItem(storageKey)&&localStorage.getItem('crmTechnimat'))localStorage.setItem(storageKey,localStorage.getItem('crmTechnimat'));
const allRepresentativeProspects=window.CRM_REPRESENTATIVE_CLIENTS?.manager||[];
let managerAssignments={},managerClientEdits={};
try{managerAssignments=JSON.parse(localStorage.getItem('crmTechnimat:clientAssignments')||'{}');managerClientEdits=JSON.parse(localStorage.getItem('crmTechnimat:sharedClientEdits')||'{}')}catch{}
const originalRepresentative=p=>['vincent','cedric','zavier'].find(id=>(window.CRM_REPRESENTATIVE_CLIENTS?.[id]||[]).some(item=>String(item.i)===String(p.i)));
const representativeProspects=activeUser==='manager'?allRepresentativeProspects:allRepresentativeProspects.filter(p=>(managerAssignments[p.i]||originalRepresentative(p))===activeUser);
const rawProspects=representativeProspects;
const prospects=rawProspects.map((p,n)=>({id:p.i||p.s||String(n+1),name:p.c||'Entreprise sans nom',siret:p.s||'',address:p.a||'',dept:p.d||'',manager:p.m&&p.m!=='x'?p.m:'',email:p.e&&p.e!=='x'&&!/^\d/.test(p.e)?p.e:'',phone:p.p&&p.p!=='x'?p.p:'',status:p.t||'Non visité'}));
prospects.forEach(p=>Object.assign(p,managerClientEdits[p.id]||{}));
const seedHistory=(activeUser==='vincent'?(window.CRM_SEED?.history||[]):[]).map((v,n)=>({id:'seed-'+n,companyId:v.siret||v.company,companyName:v.company,date:v.date,person:v.person,role:v.function,summary:v.summary,needs:v.needs,next:v.nextAction,followup:v.followupDate}));
const saved=JSON.parse(localStorage.getItem(storageKey)||'{}');
const state={prospects,history:Array.isArray(saved.history)?saved.history:seedHistory,tour:saved.tour||[],orders:saved.orders||0,newContacts:saved.newContacts||0};
window.CRM_PROSPECTS=state.prospects;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const save=()=>localStorage.setItem(storageKey,JSON.stringify({history:state.history,tour:state.tour,orders:state.orders,newContacts:state.newContacts,customProspects:state.customProspects||[],prospectEdits:state.prospectEdits||{}}));
function go(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('.bottom button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));window.scrollTo(0,0);if(id==='prospects')renderProspects();if(id==='historique')renderHistory();if(id==='tournee')renderTour();if(id==='relances')renderRelances();}
$$('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function cleanPhone(v){return String(v||'').split('/')[0].replace(/[^0-9+]/g,'')}
function companyById(id){return state.prospects.find(p=>String(p.id)===String(id))}
function renderDashboard(){const now=new Date(),greeting=document.querySelector('.hero p'),owner=document.querySelector('.brand small');if(greeting)greeting.textContent=`Bonjour ${window.CRM_USER_NAME||''}`;if(owner)owner.textContent=window.CRM_USER_NAME||'';$('#today').textContent=now.toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'});$('#ordersCount').textContent=state.orders;$('#contactsCount').textContent=state.newContacts;$('#visitsCount').textContent=state.history.length;$('#prospectsCount').textContent=state.prospects.length;const due=managerSettings.notifications===false?[]:state.history.filter(v=>v.followup&&new Date(v.followup+'T23:59:59')<=new Date()).sort((a,b)=>a.followup.localeCompare(b.followup)).slice(0,4);$('#priorityList').innerHTML=managerSettings.notifications===false?'<p class="empty">Les alertes sont désactivées par le Manager.</p>':due.length?due.map(v=>`<div class="item"><h3>${esc(v.companyName)}</h3><p>${esc(v.next||'Relance à effectuer')}</p><div class="badges"><span class="badge red">À relancer</span></div></div>`).join(''):'<p class="empty">Aucune relance enregistrée pour le moment.</p>'}
function initFilters(){const depts=[...new Set(state.prospects.map(p=>p.dept).filter(Boolean))].sort();$('#deptFilter').innerHTML='<option value="">Tous départements</option>'+depts.map(d=>`<option value="${esc(d)}">Département ${esc(d)}</option>`).join('')}
function renderProspects(){const q=($('#searchInput')?.value||'').toLowerCase().trim();const d=$('#deptFilter')?.value||'';const list=state.prospects.filter(p=>(!d||p.dept===d)&&(!q||[p.name,p.address,p.manager,p.email,p.phone,p.siret].join(' ').toLowerCase().includes(q)));$('#countLabel').textContent=`${list.length} entreprise${list.length>1?'s':''}`;$('#prospectList').innerHTML=list.length?list.map(p=>`<article class="item"><h3>${esc(p.name)}</h3><p>${esc(p.address)}</p><div class="badges"><span class="badge">${esc(p.dept||'—')}</span><span class="badge ${p.status==='À relancer'?'red':''}">${esc(p.status)}</span></div><div class="item-actions"><button onclick="openCompany('${esc(p.id)}')">Voir la fiche</button>${p.phone?`<button class="secondary" onclick="location.href='tel:${cleanPhone(p.phone)}'">Appeler</button>`:''}</div></article>`).join(''):'<p class="empty">Aucune entreprise trouvée.</p>'}
window.openCompany=id=>{const p=companyById(id);if(!p)return;const visits=state.history.filter(v=>String(v.companyId)===String(p.id)||String(v.companyName).toLowerCase()===String(p.name).toLowerCase());$('#companyName').textContent=p.name;$('#companyBody').innerHTML=`<p><strong>Statut :</strong> ${esc(p.status)}</p><p><strong>SIRET :</strong> ${esc(p.siret||'Non renseigné')}</p><p><strong>Adresse :</strong><br>${esc(p.address||'Non renseignée')}</p><p><strong>Dirigeant / contact :</strong><br>${esc(p.manager||'Non renseigné')}</p><p><strong>Téléphone :</strong><br>${p.phone?`<a href="tel:${cleanPhone(p.phone)}">${esc(p.phone)}</a>`:'Non renseigné'}</p><p><strong>E-mail :</strong><br>${p.email?`<a href="mailto:${esc(p.email)}">${esc(p.email)}</a>`:'Non renseigné'}</p><div class="row"><button onclick="addToTour('${esc(p.id)}')">Ajouter à la tournée</button><button class="ghost dark" onclick="openVisitFor('${esc(p.id)}')">Compte rendu</button></div><h3>Historique (${visits.length})</h3>${visits.length?visits.map(v=>`<div class="item"><b>${esc(v.date)}</b><p>${esc(v.summary)}</p></div>`).join(''):'<p class="mini">Aucune visite enregistrée.</p>'}`;$('#companyDialog').showModal()}
window.addToTour=id=>{if(!state.tour.includes(id))state.tour.push(id);save();alert('Entreprise ajoutée à la tournée.');}
window.openVisitFor=id=>{$('#companyDialog').close();openVisit(id)};
function openVisit(id='',date=''){const sel=$('#visitCompany');sel.innerHTML=state.prospects.map(p=>`<option value="${esc(p.id)}" ${String(p.id)===String(id)?'selected':''}>${esc(p.name)}</option>`).join('');$('#visitDate').value=date||new Date().toISOString().slice(0,10);$('#visitDialog').showModal()}
window.openVisitFromPlanning=(id,date)=>openVisit(id,date);
function renderHistory(){const h=[...state.history].sort((a,b)=>String(b.date).localeCompare(String(a.date)));$('#historyList').innerHTML=h.length?h.map(v=>`<article class="item"><h3>${esc(v.companyName)}</h3><p>${esc(v.date)} — ${esc(v.person||'Interlocuteur non précisé')}</p><p>${esc(v.summary)}</p>${v.followup?`<span class="badge red">Relance ${esc(v.followup)}</span>`:''}</article>`).join(''):'<p class="empty">Aucun compte rendu enregistré.</p>'}
function renderTour(){const list=state.tour.map(companyById).filter(Boolean);$('#tourList').innerHTML=list.length?list.map((p,i)=>`<article class="item"><h3>${i+1}. ${esc(p.name)}</h3><p>${esc(p.address)}</p><div class="item-actions"><button class="secondary" onclick="removeTour('${esc(p.id)}')">Retirer</button></div></article>`).join(''):'<p class="empty">Votre tournée est vide.</p>'}
window.removeTour=id=>{state.tour=state.tour.filter(x=>String(x)!==String(id));save();renderTour()}
function renderRelances(){const chosen=$('#relanceDate')?.value;let list=state.history.filter(v=>v.followup);if(chosen)list=list.filter(v=>v.date===chosen||v.followup===chosen);list.sort((a,b)=>a.followup.localeCompare(b.followup));$('#relanceResults').innerHTML=list.length?list.map(v=>`<article class="relance-card"><h3>${esc(v.companyName)}</h3><p><b>Pourquoi :</b> ${esc(v.summary)}</p><p><b>Action :</b> ${esc(v.next||'Appeler le prospect')}</p><p><b>Priorité :</b> ${new Date(v.followup+'T23:59:59')<=new Date()?'Haute':'À planifier'}</p><p><b>Date :</b> ${esc(v.followup)}</p><blockquote>Bonjour, ${esc(window.CRM_USER_NAME||'')} de Technimat. Je vous appelle à la suite de notre dernier échange afin de faire le point sur ${esc(v.needs||'vos besoins')}.</blockquote></article>`).join(''):'<p class="empty">Aucune relance trouvée pour cette date.</p>'}
$('#searchInput').addEventListener('input',renderProspects);$('#deptFilter').addEventListener('change',renderProspects);$('#newVisitBtn').onclick=()=>openVisit();$('#addVisit').onclick=()=>openVisit();
$('#visitForm').addEventListener('submit',e=>{e.preventDefault();const p=companyById($('#visitCompany').value);if(!p)return;state.history.push({id:Date.now(),companyId:p.id,companyName:p.name,date:$('#visitDate').value,person:$('#visitPerson').value,role:$('#visitFunction').value,contactMethod:$('#visitContactMethod').value,summary:$('#visitSummary').value,needs:$('#visitNeeds').value,next:$('#visitNext').value,bestTime:$('#visitBestTime').value,followup:$('#visitFollowup').value});if($('#visitOrder').checked)state.orders++;if($('#visitNewContact').checked)state.newContacts++;save();$('#visitDialog').close();e.target.reset();renderDashboard();renderHistory()});
$('#clearTour').onclick=()=>{state.tour=[];save();renderTour()};$('#suggestTour').onclick=()=>{const d=$('#deptFilter').value||'31';state.tour=state.prospects.filter(p=>p.dept===d&&p.status!=='Client').slice(0,Number(managerSettings.tourSize)||6).map(p=>p.id);save();renderTour()};$('#openMaps').onclick=()=>{const list=state.tour.map(companyById).filter(Boolean);if(!list.length)return alert('Ajoutez des entreprises à la tournée.');const start=encodeURIComponent($('#startAddress').value||'TECHNIMAT Narbonne');const dest=encodeURIComponent(list[list.length-1].address);const way=list.slice(0,-1).map(p=>encodeURIComponent(p.address)).join('%7C');location.href=`https://www.google.com/maps/dir/?api=1&origin=${start}&destination=${dest}${way?`&waypoints=${way}`:''}&travelmode=driving`};
$('#analyzeRelances').onclick=renderRelances;
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e});$('#installBtn')?.addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else alert('Sur iPhone : touchez Partager puis « Sur l’écran d’accueil ».')});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
if($('#startAddress'))$('#startAddress').value=managerSettings.startAddress||'TECHNIMAT, Narbonne';
initFilters();renderDashboard();renderProspects();renderHistory();
