(()=>{
  const wait=()=>{
    const planning=document.querySelector('#planning');
    const addBtn=document.querySelector('#addPlanningEvent');
    if(!planning||!addBtn)return setTimeout(wait,200);

    const style=document.createElement('style');
    style.textContent=`.voice-planner{margin:14px 0;padding:16px;background:#fff;border:1px solid #e5e7eb;border-radius:18px}.voice-planner h2{margin:0 0 5px}.voice-planner p{margin:0 0 12px;color:#666}.voice-row{display:flex;gap:8px;align-items:stretch}.voice-row textarea{flex:1;min-height:110px}.mic-btn{min-width:58px;font-size:24px}.mic-btn.listening{background:#b3131b;animation:pulse 1s infinite}.voice-actions{display:flex;gap:8px;margin-top:10px;flex-wrap:wrap}.voice-preview{margin-top:12px}.voice-preview .item{margin:7px 0;padding:10px;border:1px solid #eee;border-radius:12px}.voice-preview .route-step{background:#f7f7f7;border-style:dashed}.voice-status{font-size:13px;margin-top:8px;color:#555}.finish-dictation{display:none;background:#111;color:#fff}.finish-dictation.visible{display:inline-block}.smart-note{font-size:12px;padding:8px;border-radius:9px;margin-top:7px}.smart-note.ok{color:#155724;background:#eaf7ee}.smart-note.warn{color:#7a3d00;background:#fff1db}.smart-note.bad{color:#8a1010;background:#ffe7e7}.route-line{font-size:12px;color:#333;margin-top:6px}.hours-link{display:inline-block;margin-top:5px;font-size:12px}@keyframes pulse{50%{opacity:.65}}@media(max-width:600px){.voice-row{flex-direction:column}.mic-btn{width:100%}}`;
    document.head.appendChild(style);

    const box=document.createElement('div');
    box.className='voice-planner';
    box.innerHTML=`<h2>Assistant intelligent de journée</h2><p>Décrivez votre journée. L’assistant calcule les trajets depuis TECHNIMAT, vérifie les horaires et prévoit le retour au magasin.</p><div class="voice-row"><textarea id="dayPrompt" placeholder="Exemple : jeudi BSA à 9 h, ajoute des prospects proches et je veux être de retour à Narbonne à 16 h…"></textarea><button type="button" id="voiceMic" class="mic-btn" aria-label="Dicter ma journée">🎙️</button></div><div class="voice-actions"><button type="button" id="finishDictation" class="finish-dictation">Dictée terminée</button><button type="button" id="analyseDay">Préparer intelligemment</button><button type="button" id="createDay" class="ghost dark" disabled>Ajouter au planning</button></div><div id="voiceStatus" class="voice-status"></div><div id="voicePreview" class="voice-preview"></div>`;
    addBtn.before(box);

    const prompt=document.querySelector('#dayPrompt'),status=document.querySelector('#voiceStatus'),preview=document.querySelector('#voicePreview'),create=document.querySelector('#createDay');
    let proposals=[],routeSummary={outbound:null,return:null,conflicts:0,unavailable:0,returnDeadline:null};
    const TECH={name:'TECHNIMAT',address:'2 rue Émile Levassor, 11100 Narbonne',lat:43.1843,lon:3.0031};
    const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
    const aliases={epe:'entreprise peinture et enduits',entreprisepeintureenduit:'entreprise peinture et enduits',mcprojet:'m c projec',mcprojec:'m c projec',bsa:'bsa occitanie',etr:'entreprise de travaux et de ravalement',ite:'i.t.e sud-ouest',mpf:'midi pyrenees facades'};
    const cityCoords={narbonne:[43.1843,3.0031],toulouse:[43.6047,1.4442],carcassonne:[43.2130,2.3491],auterive:[43.3517,1.4747],muret:[43.4600,1.3250],cugnaux:[43.5364,1.3443],colomiers:[43.6108,1.4986],plaisancedutouch:[43.5657,1.2960],portetsurgaronne:[43.5239,1.4060],castanettolosan:[43.5156,1.4980],deyme:[43.4719,1.5260],pennautier:[43.2458,2.3185],limoux:[43.0548,2.2180],rieuxvolvestre:[43.2576,1.1970],fontenilles:[43.5539,1.1900],fronton:[43.8402,1.3890],lunion:[43.6578,1.4840],saintalban:[43.6922,1.4100],labarthesurleze:[43.4510,1.4010]};
    const companyList=()=>{
      const all=[];
      (window.state?.prospects||[]).forEach(p=>all.push({id:p.id,name:p.name,address:p.address||'',dept:String(p.dept||''),status:p.status||p.type||''}));
      (window.RP||[]).forEach(p=>all.push({id:p.i||p.s,name:p.c,address:p.a||'',dept:String(p.d||''),status:p.t||''}));
      const seen=new Map();all.forEach(p=>{const k=normalize(p.id||p.name);if(!seen.has(k))seen.set(k,p);else seen.set(k,{...seen.get(k),...Object.fromEntries(Object.entries(p).filter(([,v])=>v))})});return [...seen.values()].filter(p=>p.name)
    };
    const iso=d=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};
    function resolveDate(text){const now=new Date(),n=normalize(text);if(n.includes('demain')){now.setDate(now.getDate()+1);return iso(now)}if(n.includes('apresdemain')){now.setDate(now.getDate()+2);return iso(now)}const names=['dimanche','lundi','mardi','mercredi','jeudi','vendredi','samedi'];const found=names.findIndex(x=>n.includes(x));if(found>=0){let add=(found-now.getDay()+7)%7;if(add===0)add=7;now.setDate(now.getDate()+add);return iso(now)}const m=text.match(/\b(\d{1,2})[\/\-.](\d{1,2})(?:[\/\-.](\d{2,4}))?\b/);if(m){let y=m[3]?Number(m[3]):now.getFullYear();if(y<100)y+=2000;return `${y}-${String(m[2]).padStart(2,'0')}-${String(m[1]).padStart(2,'0')}`}return iso(now)}
    function timeFrom(s){const m=s.match(/\b(?:a|à|vers)?\s*(\d{1,2})(?:\s*(?:h|:|heure(?:s)?)\s*(\d{1,2})?)\b/i);if(!m)return null;return `${String(Math.min(23,+m[1])).padStart(2,'0')}:${String(m[2]||0).padStart(2,'0')}`}
    function returnDeadline(text){const m=text.match(/(?:retour|etre|être|arriver|rentrer)[^.;,]{0,35}?(?:narbonne|technimat|magasin)[^.;,]{0,20}?(?:a|à|avant)\s*(\d{1,2})(?:\s*(?:h|:|heure(?:s)?)\s*(\d{1,2})?)?/i)||text.match(/(?:a|à|avant)\s*(\d{1,2})(?:\s*(?:h|:|heure(?:s)?)\s*(\d{1,2})?)?[^.;,]{0,25}?(?:narbonne|technimat|magasin)/i);return m?`${String(+m[1]).padStart(2,'0')}:${String(m[2]||0).padStart(2,'0')}`:null}
    function addMinutes(t,n){let total=mins(t)+n;total=Math.max(0,total);return `${String(Math.floor(total/60)%24).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`}
    function mins(t){const[h,m]=t.split(':').map(Number);return h*60+m}
    function findCompany(segment){let ns=normalize(segment);for(const[a,b]of Object.entries(aliases))if(ns.includes(a))ns+=' '+normalize(b);let best=null,score=0;for(const c of companyList()){const nc=normalize(c.name);if(!nc)continue;let sc=ns.includes(nc)?100+nc.length:0;for(const[a,b]of Object.entries(aliases))if(ns.includes(a)&&nc.includes(normalize(b)))sc=Math.max(sc,150);const words=c.name.toLowerCase().split(/\s+/).map(normalize).filter(w=>w.length>1);const hits=words.filter(w=>ns.includes(w)).length;sc=Math.max(sc,hits*12);if(sc>score){score=sc;best=c}}return score>=12?best:null}
    const plannedFor=date=>JSON.parse(localStorage.getItem('crmPlanning')||'[]').filter(e=>e.date===date);
    function pickSuggestions(date,kind,dept,exclude){const existing=new Set([...plannedFor(date),...proposals].map(e=>normalize(e.company||'')));const visits=window.state?.visits||[];const visited=new Set(visits.map(v=>String(v.companyId||'')));return companyList().filter(c=>{if(existing.has(normalize(c.name))||exclude.has(normalize(c.name)))return false;if(dept&&c.dept&&c.dept!==dept)return false;const st=normalize(c.status);if(kind==='relance')return /relancer|suivre|devis|attente/.test(st);return /nonvisite|prospect/.test(st)||(!visited.has(String(c.id))&&!/relancer/.test(st))}).sort((a,b)=>a.name.localeCompare(b.name,'fr'))}
    function freeSlots(date){const busy=[...plannedFor(date),...proposals].map(e=>[mins(e.start),mins(e.end)]).sort((a,b)=>a[0]-b[0]);const windows=[[8*60,12*60],[13*60+30,17*60+30]],slots=[];for(const[ws,we]of windows){let cur=ws;for(const[s,e]of busy){if(e<=ws||s>=we)continue;if(s-cur>=75)slots.push(cur);cur=Math.max(cur,e+15)}while(we-cur>=60){slots.push(cur);cur+=75}}return slots.map(m=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`)}
    function recFrom(company,date,start,title,notes){return{id:'smart-'+Date.now()+'-'+Math.random().toString(36).slice(2),companyId:company?.id||'',company:company?.name||'',title,date,start,end:addMinutes(start,title==='Pause déjeuner'?60:45),address:company?.address||'',notes,travelMinutes:null,distanceKm:null,feasible:true,feasibilityText:'',fromName:''}}

    const geoCache=JSON.parse(localStorage.getItem('crmGeoCache')||'{}');
    function fallbackPoint(address){const n=normalize(address);for(const[c,[lat,lon]]of Object.entries(cityCoords))if(n.includes(c))return{lat,lon};const cp=(address.match(/\b(11|31|34|66)\d{3}\b/)||[])[0];if(cp?.startsWith('31'))return{lat:43.6047,lon:1.4442};if(cp?.startsWith('11'))return{lat:43.2130,lon:2.3491};if(cp?.startsWith('34'))return{lat:43.6108,lon:3.8767};if(cp?.startsWith('66'))return{lat:42.6887,lon:2.8948};return null}
    async function geocode(address){if(!address)return null;if(normalize(address).includes('2rueemilelevassor'))return{lat:TECH.lat,lon:TECH.lon};const key=normalize(address);if(geoCache[key])return geoCache[key];const fallback=fallbackPoint(address);try{const r=await Promise.race([fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=fr&q=${encodeURIComponent(address)}`),new Promise((_,rej)=>setTimeout(()=>rej(new Error('timeout')),3500))]);const d=await r.json();if(d?.[0]){const point={lat:+d[0].lat,lon:+d[0].lon};geoCache[key]=point;localStorage.setItem('crmGeoCache',JSON.stringify(geoCache));return point}}catch(e){}return fallback}
    function haversine(a,b){const R=6371,toRad=x=>x*Math.PI/180,dLat=toRad(b.lat-a.lat),dLon=toRad(b.lon-a.lon),q=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
    async function routeBetween(a,b){const pa=await geocode(a),pb=await geocode(b);if(!pa||!pb)return null;try{const r=await Promise.race([fetch(`https://router.project-osrm.org/route/v1/driving/${pa.lon},${pa.lat};${pb.lon},${pb.lat}?overview=false`),new Promise((_,rej)=>setTimeout(()=>rej(new Error('timeout')),4500))]);const d=await r.json(),x=d?.routes?.[0];if(x)return{minutes:Math.ceil(x.duration/60),km:Math.round(x.distance/100)/10,estimated:false}}catch(e){}const straight=haversine(pa,pb),km=Math.max(2,straight*1.28),speed=km>80?82:km>25?65:42;return{minutes:Math.ceil(km/speed*60),km:Math.round(km*10)/10,estimated:true}}
    async function analyseRoutes(text){proposals.sort((a,b)=>a.start.localeCompare(b.start));routeSummary={outbound:null,return:null,conflicts:0,unavailable:0,returnDeadline:returnDeadline(text)};let previous={company:TECH.name,address:TECH.address,end:'07:00'};for(const p of proposals){if(!p.address){previous={...p,address:previous.address,company:p.title};continue}status.textContent=`Calcul du trajet ${previous.company} → ${p.company}…`;const route=await routeBetween(previous.address,p.address);p.fromName=previous.company;if(!route){p.feasibilityText=`Trajet depuis ${previous.company} non calculable.`;routeSummary.unavailable++;previous=p;continue}p.travelMinutes=route.minutes;p.distanceKm=route.km;p.routeEstimated=route.estimated;if(!routeSummary.outbound)routeSummary.outbound={...route,to:p.company};const earliest=mins(previous.end)+route.minutes+10,scheduled=mins(p.start);if(earliest>scheduled){p.feasible=false;p.suggestedStart=addMinutes('00:00',earliest);p.feasibilityText=`Impossible à ${p.start} : départ après ${previous.company} à ${previous.end}, arrivée réaliste vers ${p.suggestedStart}.`;routeSummary.conflicts++}else{p.feasible=true;p.feasibilityText=`Possible : ${route.minutes} min de route + 10 min de marge, soit ${scheduled-earliest} min d’avance.`}previous=p}
      const last=[...proposals].reverse().find(p=>p.address);if(last){status.textContent=`Calcul du retour ${last.company} → TECHNIMAT…`;const back=await routeBetween(last.address,TECH.address);if(back){const arrival=addMinutes(last.end,back.minutes+10);routeSummary.return={...back,from:last.company,depart:last.end,arrival};if(routeSummary.returnDeadline&&mins(arrival)>mins(routeSummary.returnDeadline)){routeSummary.conflicts++;routeSummary.return.conflict=true}}else routeSummary.unavailable++}
      return routeSummary
    }
    function renderPreview(){let html='';if(proposals.length){const first=proposals.find(p=>p.address);html+=`<article class="item route-step"><h3>🚐 Départ de TECHNIMAT</h3><p><strong>${TECH.address}</strong></p>${routeSummary.outbound?`<div class="route-line">Départ conseillé : ${addMinutes(first.start,-routeSummary.outbound.minutes-10)} · ${routeSummary.outbound.minutes} min · ${routeSummary.outbound.km} km jusqu’à ${routeSummary.outbound.to}</div>`:'<div class="smart-note warn">Calcul du premier trajet en cours ou indisponible.</div>'}</article>`}
      html+=proposals.map((x,i)=>`<article class="item"><h3>${x.start}–${x.end} · ${x.title}</h3><p><strong>${x.company||'Pause'}</strong>${x.address?'<br>'+x.address:''}</p>${x.travelMinutes!=null?`<div class="route-line">🚗 Depuis ${x.fromName} : ${x.travelMinutes} min · ${x.distanceKm} km${x.routeEstimated?' (estimation)':''}</div>`:''}<div class="smart-note ${x.feasible===false?'bad':x.travelMinutes==null&&x.address?'warn':'ok'}">${x.feasibilityText||'Créneau préparé.'}</div>${x.feasible===false?`<button type="button" class="apply-time" data-i="${i}">Décaler à ${x.suggestedStart}</button>`:''}${x.company?`<br><a class="hours-link" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent((x.company||'')+' '+(x.address||''))}">Vérifier les horaires sur Google Maps</a>`:''}</article>`).join('');
      if(routeSummary.return)html+=`<article class="item route-step"><h3>🏁 Retour à TECHNIMAT</h3><p><strong>Départ de ${routeSummary.return.from} à ${routeSummary.return.depart}</strong><br>${TECH.address}</p><div class="route-line">🚗 ${routeSummary.return.minutes} min · ${routeSummary.return.km} km · arrivée estimée ${routeSummary.return.arrival}</div><div class="smart-note ${routeSummary.return.conflict?'bad':'ok'}">${routeSummary.return.conflict?`Retour impossible avant ${routeSummary.returnDeadline}. Arrivée estimée à ${routeSummary.return.arrival}.`:`Retour prévu à ${routeSummary.return.arrival}${routeSummary.returnDeadline?' avant votre limite de '+routeSummary.returnDeadline:''}.`}</div></article>`;
      preview.innerHTML=html||'<p class="empty">Aucun rendez-vous reconnu.</p>';preview.querySelectorAll('.apply-time').forEach(b=>b.addEventListener('click',()=>{const p=proposals[+b.dataset.i];p.start=p.suggestedStart;p.end=addMinutes(p.start,p.title==='Pause déjeuner'?60:45);parse()}))
    }
    async function parse(){const text=prompt.value.trim();if(!text){status.textContent='Décrivez d’abord votre journée.';return}create.disabled=true;const date=resolveDate(text);let cursor='08:00';proposals=[];const excluded=new Set();const parts=text.split(/(?:,|;|\bpuis\b|\bensuite\b|\baprès\b|\bet après\b)/i).map(x=>x.trim()).filter(Boolean);for(const part of parts){const explicit=timeFrom(part);if(explicit)cursor=explicit;const pause=/pause|dejeuner|déjeuner|repas/i.test(part);const askFill=/ajoute|propose|complete|complète|remplis|remplir/.test(normalize(part))&&/prospect|journee|journée|creneau|créneau|relance/.test(normalize(part));if(askFill)continue;const company=pause?null:findCompany(part);if(company)excluded.add(normalize(company.name));if(pause)proposals.push(recFrom(null,date,cursor,'Pause déjeuner',part));else if(company){const title=/livraison/i.test(part)?'Livraison':(/relance|appeler|appel/i.test(part)?'Relance téléphonique':'Visite commerciale');proposals.push(recFrom(company,date,cursor,title,part))}cursor=addMinutes(proposals.at(-1)?.end||cursor,15)}const n=normalize(text),wantsProspects=/prospect|complete.*journee|journee.*pas.*pleine|remplis.*journee/.test(n),wantsRelances=/relance/.test(n)&&/ajoute|propose|complete|remplis|prioritaire/.test(n);if(wantsProspects||wantsRelances){const dept=(proposals.find(p=>p.companyId)&&companyList().find(c=>String(c.id)===String(proposals.find(p=>p.companyId).companyId))?.dept)||'';let slots=freeSlots(date),kinds=wantsRelances&&wantsProspects?['relance','prospect']:wantsRelances?['relance']:['prospect'],ki=0;while(slots.length&&ki<10){const kind=kinds[ki%kinds.length],c=pickSuggestions(date,kind,dept,excluded)[0];if(!c){ki++;continue}excluded.add(normalize(c.name));proposals.push(recFrom(c,date,slots.shift(),kind==='relance'?'Relance commerciale':'Prospection',`Suggestion intelligente : ${kind}`));ki++}}proposals.sort((a,b)=>a.start.localeCompare(b.start));renderPreview();const report=await analyseRoutes(text);renderPreview();status.textContent=`${proposals.length} élément(s) préparé(s). ${report.conflicts?report.conflicts+' conflit(s) détecté(s).':'Horaires réalisables.'}${report.unavailable?' '+report.unavailable+' trajet(s) non calculé(s).':''} Les estimations de secours sont hors trafic en direct.`;create.disabled=!proposals.length||report.conflicts>0}
    document.querySelector('#analyseDay').addEventListener('click',parse);
    create.addEventListener('click',()=>{const current=JSON.parse(localStorage.getItem('crmPlanning')||'[]'),keys=new Set(current.map(e=>`${e.date}|${e.start}|${normalize(e.company||e.title)}`));let added=0;for(const p of proposals){const k=`${p.date}|${p.start}|${normalize(p.company||p.title)}`;if(!keys.has(k)){current.push(p);keys.add(k);added++}}localStorage.setItem('crmPlanning',JSON.stringify(current));status.textContent=`${added} rendez-vous ajouté(s).`;setTimeout(()=>location.reload(),700)});

    const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition,mic=document.querySelector('#voiceMic'),finish=document.querySelector('#finishDictation');
    if(!SpeechRecognition){mic.disabled=true;status.textContent='La saisie écrite fonctionne. Pour la dictée, utilisez Chrome ou Safari récent.'}
    else{const rec=new SpeechRecognition();rec.lang='fr-FR';rec.continuous=true;rec.interimResults=true;let shouldListen=false,committed='',starting=false;const startRecognition=()=>{if(!shouldListen||starting)return;starting=true;try{rec.start()}catch(e){starting=false}};mic.addEventListener('click',()=>{if(shouldListen)return;committed=prompt.value.trim();shouldListen=true;finish.classList.add('visible');status.textContent='Je vous écoute…';startRecognition()});finish.addEventListener('click',()=>{shouldListen=false;finish.classList.remove('visible');try{rec.stop()}catch(e){}status.textContent='Dictée terminée. Appuyez sur « Préparer intelligemment ».'});rec.onstart=()=>{starting=false;mic.classList.add('listening')};rec.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript.trim();if(e.results[i].isFinal)committed=[committed,t].filter(Boolean).join(' ').trim();else interim=[interim,t].filter(Boolean).join(' ')}prompt.value=[committed,interim].filter(Boolean).join(' ').trim()};rec.onend=()=>{starting=false;mic.classList.remove('listening');if(shouldListen)setTimeout(startRecognition,250)};rec.onerror=e=>{starting=false;mic.classList.remove('listening');if(e.error==='no-speech'&&shouldListen){setTimeout(startRecognition,300);return}shouldListen=false;finish.classList.remove('visible');status.textContent='Microphone indisponible : '+e.error}};
  };wait();
})();